export enum SUPPORT_FORM_SIDE_EFFECTS {
  FETCH_SENTINEL_DATA,
  REDIRECT_TO_SUPPORT_LANDING_PAGE,
  SUBMIT_TO_SFDC
}

export enum SUPPORT_FORM_STEPS {
  UNDEFINED,
  UNITIALIZED,
  GUEST_START,
  SELECT_PATIENT,
  ACKNOWLEDGE_NOT_SAE,
  SELECT_INSERTION_SITE,
  SELECT_ISSUE_DATE,
  SELECT_YOUR_DEVICE,
  SELECT_ISSUE_CATEGORY,
  SELECT_SENTINEL_PRODUCT,
  SPECIFY_PRODUCT,
  SENTINEL_SHOW_SPECIFY_PRODUCT,
  TSG_INTERVIEW,
  COLLECT_USER_INFO,
  CONFIRM_SUBMISSION,
}

export enum SUPPORT_FORM_ACTIONS {
  INITIALIZE,
  SELECT_PATIENT,
  ACKNOWLEDGE_NOT_SAE,
  SELECT_INSERTION_LOCATION,
  SELECT_ISSUE_DATE,
  SELECT_ISSUE_CATEGORY,
  SET_SENTINEL_PRODUCTS,
  SET_SENTINEL_MANUAL_INPUT,
  SPECIFY_PRODUCT,
  SET_PRODUCT_TYPE,
  SUBMIT_TSG_INTERVIEW,
  SUBMIT_USER_INFO,
  CONFIRM_SUBMISSION,
  EXIT_SUBMISSION,
  DEBUG_OVERRIDE_STATE,
  GUEST_REQUEST_SUPPORT,
  GO_BACK,
  RETURN_TO_GUEST_START,
  ABANDON_NAVIGATE_AWAY
}

export enum SUPPORT_FORM_MODE {
  CAREGIVER,
  DEPENDENT,
  GUEST
}
